### ISSUE TITLE
compare immutable with mutable values

### ISSUE THREAD

**Issue by gedaiu** [gedaiu/fluent-asserts#36]
`
fluent-asserts/core/fluentasserts/core/array.d(20,26): Error: cannot implicitly convert expression reference of type string[] to immutable(string)[]
`

**Comment by linkrope** [comment]
Same issue with `const` and the other way around:

    fluent-asserts/core/fluentasserts/core/array.d(20): Error: cannot implicitly convert expression reference of type const(string)[] to string[]
