### ISSUE TITLE
checks with const actual no longer compile

### ISSUE THREAD

**Issue by linkrope** [gedaiu/fluent-asserts#49]
unittest
    {
        const actual = 42;
        actual.should.equal(42);
    }

results in:

    core/fluentasserts/core/base.d(449,5): Error: cannot modify const expression r.__expand_field_0
    core/fluentasserts/core/base.d(513,39): Error: template instance fluentasserts.core.base.evaluate!(const(int)) error instantiating
    instantiated from here: should!(const(int))

(for better reference, I created an issue from my earlier comment)

**Comment by gedaiu** [comment]
thanks! i'll look into it.
