### ISSUE TITLE
make vibe dependency optional

### ISSUE THREAD

**Issue by WebFreak001** [gedaiu/fluent-asserts#72]
As you already separated it into `:vibe` it is optional already, but it could have been kept in the normal package and just adding `"optional": true` and then using `version (Have_vibe_data)`  `version (Have_vibe_http)`

Don't know if you want to change the layout again, but maybe worth considering for 1.0.0. Close if you don't want to do this

**Comment by gedaiu** [comment]
actually, this idea sounds great! I'll update the code soon as you proposed.

**Comment by WebFreak001** [comment]
hm looks like the vibe unittests got remoed because of this

**Comment by gedaiu** [comment]
how so? I just checked with `dub test` and the vibe tests were executed.

**Comment by WebFreak001** [comment]
hm meant the travis tests, but not sure anymore now

**Comment by gedaiu** [comment]
They should be executed... anyway, I the next days I will change to run the tests using trial and it will be clear what tests are run...
