### ISSUE TITLE
Large git history

### ISSUE THREAD

**Issue by BenjaminSchaaf** [gedaiu/fluent-asserts#74]
There seem to be a bunch of large-ish binary files in the git history of this project, bloating it up and thereby making initial clones much slower. It might be worth purging these from git history.

I was able to find the following binary files:
```
test/disabledDiffResult/disabled-diff-result-example
test/disabledDiffResult/disabled-message-result-example
test/disabledDiffResult/disabled-source-result-example
test/disabledMessageResult/disabled-message-result-example
test/disabledMessageResult/disabled-source-result-example
test/disabledSourceResult/disabled-source-result-example
trial-vibe
```

**Comment by gedaiu** [comment]
yes... i added them by mistake... i removed them from master and it should not be there on the next release

**Comment by BenjaminSchaaf** [comment]
My issue wasn't with the release, but with the repository. You'd have to rewrite the git history to properly remove them. It just took me a while to clone the repository :)

**Comment by gedaiu** [comment]
I see... I'm working on this

**Comment by gedaiu** [comment]
I managed to remove almost all the binaries from the history... 

there is still a problem with this one:
```
8751508ef55e20a607a3a4d352b6d64e0adf7625 7830972 test/disabledDiffResult/disabled-diff-result-example
```
and I am not really sure how to remove it...

**Comment by BenjaminSchaaf** [comment]
`filter-branch` worked for me: https://stackoverflow.com/questions/307828/completely-remove-file-from-all-git-repository-commit-history

**Comment by BenjaminSchaaf** [comment]
Awesome, thank you very much!

**Comment by gedaiu** [comment]
anytime!
