### ISSUE TITLE
Better way to check exception messages

### ISSUE THREAD

**Issue by ohdatboi** [gedaiu/fluent-asserts#8]
Currently this:
```
({
  throw new Exception("check me");
}).should.throwException!Exception.msg.should.contain("you");
```
Results in this:
```
... }).should.throwException!Exception.msg should contain `you` ...
```

I would like to see a better way to check exception messages, like this:
```
({
  throw new Exception("check me");
}).should.throwException!Exception.message.should.contain("you");
```
Which will give nice output:
```
... Message of Exception should contain `you`...
```

**Comment by gedaiu** [comment]
It's a good suggestion, but right now I don't know how I would implement it... I will think about it.

Anyway, an unit test would be helpful... 

At the dconf they said that they will write the dmd frontend as a library, which will do this task easier to implement...

**Comment by gedaiu** [comment]
@ohdatboi I made some changes to the api and the exception errors look better now... what do you think?

**Comment by ohdatboi** [comment]
@gedaiu I like it!
