### ISSUE TITLE
Deprecation of `this` as a Type

### ISSUE THREAD

**Issue by vnayar** [gedaiu/fluent-asserts#86]
Since DMD v2.083.1, a large number of compilation warnings in the format below have been observed:

```
../../.dub/packages/fluent-asserts-0.9.0/fluent-asserts/core/fluentasserts/core/basetype.d(22,17): Deprecation: Using this as a type is deprecated. Use typeof(this) instead
```

**Comment by gedaiu** [comment]
it looks like you use an older version. Does it work with the latest one?

**Comment by vnayar** [comment]
Ah, you are correct, the version of Fluent-Asserts itself skipped my mind.  I was using 0.9.0.  Everything works find with 0.12.3.
