### ISSUE TITLE
Move vibe.d support to a separate package

### ISSUE THREAD

**Issue by ghost91-** [gedaiu/fluent-asserts#89]
Currently when using fluent-asserts, vibe.d is always pulled in as a dependency. This is very undesirable for projects which do not use vibe.d by themselves because it massively increases build times.

As a solution, I propose to move the vibe.d support of fluent-asserts to a separate package (fluent-assets-vibe-d) which itself depends on fluent-asserts. Projects which don't need the vibe.d support could then simply use the basic fluent-asserts package and projects which need the vibe.d support would use fluent-assets-vibe-d.

**Comment by gedaiu** [comment]
hmm.. I was thinking about this for a while, and since the dub dependencies will not be fixed for a while, I think I'll go on this path. 

Thanks!

**Comment by jll63** [comment]
Same problem here, I was giving fluent-asserts a spin, it downloaded vibe and a lot of stuff, and now it complains that:

```
/usr/bin/ld: cannot find -lssl
/usr/bin/ld: cannot find -lcrypto
collect2: error: ld returned 1 exit status
```

**Comment by gedaiu** [comment]
Done. You can try the new v0.13.0
